name: "Check - URL - Ping"
description: "Action to run ping check on given URL."
author: hoverkraft
branding:
  icon: activity
  color: blue

inputs:
  url:
    description: "The URL to check."
    required: true
  follow-redirect:
    description: "Whether to follow redirects."
    required: false
    default: "false"
  timeout:
    description: "Timeout in seconds for the full URL check process."
    required: false
    default: "60"
  retries:
    description: "Total number of attempts allowed for the URL check process."
    required: false
    default: "3"
  expected-statuses:
    description: "Expected HTTP status codes. Comma separated list."
    required: false
    default: "200"
  authorization:
    description: |
      Optional Authorization header used to access private URLs.
      Examples: `Bearer xxx...`, `token xxx...`
    required: false
    default: ""

outputs:
  status-code:
    description: "The HTTP status code returned by the URL check."
    value: ${{ steps.check-url.outputs.status-code }}
  attempt-count:
    description: "Total number of attempts performed before completion."
    value: ${{ steps.check-url.outputs.attempt-count }}

runs:
  using: composite
  steps:
    - id: check-url
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const path = require('path');
          const { run } = require(path.join(process.env.GITHUB_ACTION_PATH, 'index.js'));

          await run({
            core,
            inputs: {
              url: ${{ toJson(inputs.url ) }},
              followRedirect: ${{ toJson(inputs['follow-redirect']) }},
              timeout: ${{ toJson(inputs.timeout) }},
              retries: ${{ toJson(inputs.retries) }},
              expectedStatuses: ${{ toJson(inputs['expected-statuses']) }},
              authorization: ${{ toJson(inputs.authorization) }},
            },
          });
