name: "Deployment - Delete deployment(s)"
description: "Action to delete some deployment(s) for the current ref. It also deletes the associated review apps environment(s) if any."
author: hoverkraft
branding:
  icon: trash-2
  color: blue

inputs:
  token:
    description: "The token to use to delete the review apps environment(s). It needs the `repo` scope."
    required: false

outputs:
  deployment-ids:
    description: "The id(s) of the deleted deployment(s). JSON array format."
    value: ${{ steps.delete-deployments.outputs.deployment-ids }}
  environments:
    description: "The name(s) of the environment(s) related to deleted deployment(s). JSON array format."
    value: ${{ steps.delete-deployments.outputs.environments }}

runs:
  using: "composite"
  steps:
    - id: delete-deployments
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const { owner, repo } = context.repo;

          const prNumber =
            context.payload?.pull_request?.number ??
            context.payload?.workflow_run?.pull_requests?.[0]?.number ??
            context.issue?.number ??
            undefined;

          let ref = context.ref;

          if (prNumber) {
            try {
              const { data: pullRequest } = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: prNumber,
              });

              ref = pullRequest?.head?.ref ?? ref;
            } catch (error) {
              return core.setFailed(
                `Failed to resolve PR head ref for #${prNumber}: ${error.message ?? error}`
              );
            }
          }

          if (!ref) {
            return core.setFailed('No ref found.');
          }

          const deployments = await github.paginate(github.rest.repos.listDeployments, {
            owner,
            repo,
            ref,
          });

          const deploymentIds = [];
          const environments = new Set();

          const { data: { html_url } } = await github.rest.actions.getWorkflowRun({
            owner,
            repo,
            run_id: context.runId,
          });

          for (const deployment of deployments) {
            await github.rest.repos.createDeploymentStatus({
              owner,
              repo,
              deployment_id: deployment.id,
              state: "inactive",
              log_url: html_url,
              auto_inactive: true,
            });

            await github.rest.repos.deleteDeployment({
              owner,
              repo,
              deployment_id: deployment.id,
            });

            deploymentIds.push(deployment.id);
            environments.add(deployment.environment);
          }

          const reviewAppsEnvironments = Array.from(environments).filter((environment) => environment.startsWith('review-apps'));

          core.setOutput('deployment-ids', JSON.stringify(deploymentIds));
          core.setOutput('environments', JSON.stringify(Array.from(environments)));
          core.setOutput('review-apps-environments', JSON.stringify(reviewAppsEnvironments));

    - id: delete-review-apps-environments
      if: steps.delete-deployments.outputs.review-apps-environments != '[]'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        REVIEW_APPS_ENVIRONMENTS: ${{ steps.delete-deployments.outputs.review-apps-environments }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const reviewAppsEnvironments = JSON.parse(process.env.REVIEW_APPS_ENVIRONMENTS);
          for (const environment of reviewAppsEnvironments) {
            // Environment may be unavailable if it was already deleted or if the token does not have access to it
            try {
              await github.rest.repos.deleteAnEnvironment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                environment_name: environment,
              });
            } catch (error) {
              if (error.status === 404) {
                core.warning(
                  `Environment "${environment}" for "${context.repo.owner}/${context.repo.repo}" cannot be deleted as it is not found`
                )
              } else {
                throw error
              }
            }
          }
