name: Deploy - Get Environment
author: hoverkraft
branding:
  icon: flag
  color: blue
description: |
  Action to get the environment to deploy regarding the workflow context.

  - If the workflow is triggered by an issue event (or pull-request):
    If an environment is given, the environment will be set to `<environment>:pr-<issue_number>`.
    If no environment is given, the environment will be set to `review-apps:pr-<issue_number>`.
  - Else if no environment is given, the action will fail.

inputs:
  environment:
    description: Environment where to deploy.
    required: false

outputs:
  environment:
    description: "The proper environment to deploy to."
    value: ${{ steps.get-environment.outputs.environment }}

runs:
  using: "composite"
  steps:
    - id: get-issue-number
      if: ${{ github.event_name == 'issue_comment' || github.event_name == 'pull_request' }}
      uses: hoverkraft-tech/ci-github-common/actions/get-issue-number@2334d395217f9811699dbd4ace9d8559e4d99e0d # 0.37.3

    - id: get-environment
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        STEP_ISSUE_NUMBER: ${{ steps.get-issue-number.outputs.issue-number }}
      with:
        script: |
          let environment = process.env.INPUT_ENVIRONMENT;
          const issueNumber = process.env.STEP_ISSUE_NUMBER;

          if (issueNumber) {
            if (!environment) {
              environment = 'review-apps';
            }

            environment = `${environment}:pr-${issueNumber}`;
          }

          if (!environment) {
            return core.setFailed('Environment not set. Please set the environment input.');
          }

          core.setOutput('environment', environment);
