name: "Deployment - Create deployment"
description: "Action to create a new deployment"
author: hoverkraft
branding:
  icon: arrow-right-circle
  color: blue

outputs:
  deployment-id:
    description: "The ID of the created deployment"
    value: ${{ steps.create-deployment.outputs.deployment-id }}

inputs:
  environment:
    description: "The environment to deploy to"
    required: true

runs:
  using: "composite"
  steps:
    - id: create-deployment
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const issueNumber = context.issue?.number ?? undefined;

          const ref = issueNumber
            ? `refs/pull/${issueNumber}/head`
            : context.ref;

          if (!ref) {
            core.setFailed('No ref found.');
            return;
          }

          const { data: deployment } = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref,
            environment: `${{ inputs.environment }}`,
            auto_merge: false,
            transient_environment: `${{ inputs.environment }}`.startsWith('review-apps'),
            required_contexts: [],
          });

          core.setOutput('deployment-id', deployment.id);
