name: "Deployment - Create deployment"
description: "Action to create a new deployment"
author: hoverkraft
branding:
  icon: arrow-right-circle
  color: blue

outputs:
  deployment-id:
    description: "The ID of the created deployment"
    value: ${{ steps.create-deployment.outputs.deployment-id }}

inputs:
  environment:
    description: "The environment to deploy to"
    required: true

runs:
  using: "composite"
  steps:
    - id: create-deployment
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        INPUTS_ENVIRONMENT: ${{ inputs.environment }}
      with:
        script: |
          const { owner, repo } = context.repo;

          const prNumber =
            context.payload?.pull_request?.number ??
            context.payload?.workflow_run?.pull_requests?.[0]?.number ??
            context.issue?.number ??
            undefined;

          let ref = context.ref;

          if (prNumber) {
            try {
              const { data: pullRequest } = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: prNumber,
              });

              ref = pullRequest?.head?.ref ?? ref;
            } catch (error) {
              return core.setFailed(
                `Failed to resolve PR head ref for #${prNumber}: ${error.message ?? error}`
              );
            }
          }

          if (!ref) {
            return core.setFailed('No ref found.');
          }

          const { data: deployment } = await github.rest.repos.createDeployment({
            owner,
            repo,
            ref,
            environment: process.env.INPUTS_ENVIRONMENT,
            auto_merge: false,
            transient_environment: process.env.INPUTS_ENVIRONMENT.startsWith('review-apps'),
            required_contexts: [],
          });

          core.setOutput('deployment-id', deployment.id);
