name: "Update deployment"
description: "Action to update a deployment. Create a new status."
author: Hoverkraft
branding:
  icon: arrow-right-circle
  color: gray-dark

inputs:
  deployment-id:
    description: "The id of the deployment to update"
    required: true
  state:
    description: "The state of the deployment"
    required: true
  description:
    description: "The description of the deployment"
    required: false
  url:
    description: "The url of the deployment"
    required: false

runs:
  using: "composite"
  steps:
    - id: create-deployment
      uses: actions/github-script@v7
      with:
        script: |
          const { data: { html_url } } = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });

          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: `${{ inputs.deployment-id }}`,
            state: `${{ inputs.state }}`,
            environment_url: `${{ inputs.url }}`,
            log_url: html_url,
            auto_inactive: true,
          });
