name: "Deployment - Update deployment"
description: "Action to update a deployment. Create a new status."
author: hoverkraft
branding:
  icon: refresh-cw
  color: blue

inputs:
  deployment-id:
    description: "The ID of the deployment to update"
    required: true
  repository:
    description: "The repository where the deployment was made"
    required: false
    default: "${{ github.event.repository.name }}"
  state:
    description: "The state of the deployment"
    required: true
  description:
    description: "The description of the deployment"
    required: false
  url:
    description: "The URL of the deployment"
    required: false
  update-log-url:
    description: "Update the log URL of the deployment"
    required: false
    default: "true"
  github-token:
    description: |
      GitHub Token to update the deployment.
      Permissions:
        - deployments: write
      See https://docs.github.com/en/rest/deployments/statuses?apiVersion=2022-11-28#create-a-deployment-status.
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - id: create-deployment
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const repository = `${{ inputs.repository }}`.trim();

          let logUrl = null;

          const shouldUpdateLogUrl = `${{ inputs.update-log-url }}`.trim();
          if (shouldUpdateLogUrl === "true") {
            const { data: { html_url } } = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: repository,
              run_id: context.runId,
            });

            logUrl = html_url;
          } 

          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: repository,
            deployment_id: `${{ inputs.deployment-id }}`,
            state: `${{ inputs.state }}`,
            environment_url: `${{ inputs.url }}`,
            log_url: logUrl ?? undefined,
            auto_inactive: true,
          });
