name: "Deployment - Create Release"
description: "Action to create a new release"
author: hoverkraft
branding:
  icon: bookmark
  color: blue

inputs:
  prerelease:
    description: "Whether the release is a prerelease"
    default: "false"
  github-token:
    description: |
      GitHub Token for creating the release.
      Permissions:
        - contents: write
    required: false
    default: ${{ github.token }}

outputs:
  tag:
    description: "The tag of the release"
    value: ${{ steps.get-tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - uses: hoverkraft-tech/ci-github-common/actions/checkout@5f11437c716059f30c635f90055060e4ef8b31a0 # 0.28.0
      with:
        fetch-depth: "0"

    - id: release
      uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        publish: true
        prerelease: ${{ inputs.pre-release }}
        disable-autolabeler: true

    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: get-tag
      with:
        script: |
          const tag = `${{ steps.release.outputs.tag_name }}`.trim();
          if (tag.length) {
            core.setOutput("tag", tag);
            return;
          }

          core.setFailed("No tag found from release-drafter outputs");
