name: "Create Release"
description: "Action to create a release"
author: Hoverkraft
branding:
  icon: bookmark
  color: gray-dark

inputs:
  token:
    description: "GitHub token"
    required: true
  prerelease:
    description: "Whether the release is a prerelease"
    default: "false"

outputs:
  version:
    description: "The version of the release"
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: hoverkraft-tech/ci-github-common/actions/checkout@0.16.1
      with:
        fetch-depth: "0"

    - id: release
      uses: release-drafter/release-drafter@v6.1.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        publish: true
        prerelease: ${{ inputs.pre-release }}
        disable-autolabeler: true

    - uses: actions/github-script@v7
      id: get-version
      with:
        script: |
          const version = `${{ steps.release.outputs.tag_name }}`.trim();
          if (tag.length) {
            core.setOutput("version", version);
            return;
          }

          core.setFailed("No version found from release-drafter outputs");
