name: "Deployment - Create Release"
description: "Action to create a new release"
author: hoverkraft
branding:
  icon: bookmark
  color: blue

inputs:
  prerelease:
    description: "Whether the release is a prerelease"
    default: "false"
  working-directory:
    description: |
      Working directory for monorepo support.
      If specified, the release configuration file will be placed in `.github/release-configs/{slug}.yml` where slug is derived from the working directory path.
      The configuration will include `include-paths` to filter pull requests to only those that modified files in the specified directory.
    type: string
    required: false
    default: ""
  github-token:
    description: |
      GitHub Token for creating the release.
      Permissions:
        - contents: write
    required: false
    default: ${{ github.token }}

outputs:
  tag:
    description: "The tag of the release"
    value: ${{ steps.get-tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: mkdir -p ./self-release-create-actions/ && cp -r $GITHUB_ACTION_PATH/../* ./self-release-create-actions/

    - id: get-configuration
      uses: ./self-release-create-actions/get-configuration
      with:
        working-directory: ${{ inputs.working-directory }}

    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: |
        rm -fr ./self-release-create-actions

    - uses: hoverkraft-tech/ci-github-common/actions/checkout@e6733528d06b6e1668674c35ef3612ac416cedda # 0.31.1
      with:
        fetch-depth: "0"

    - id: release
      uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        publish: true
        # config-name is relative to .github/ directory
        config-name: ${{ steps.get-configuration.outputs.config-name }}
        prerelease: ${{ inputs.prerelease }}
        disable-autolabeler: true
        latest: ${{ inputs.prerelease != 'true' && !inputs.working-directory && 'true' || 'false' }}

    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: get-tag
      with:
        script: |
          const tag = `${{ steps.release.outputs.tag_name }}`.trim();
          if (tag.length) {
            core.setOutput("tag", tag);
            return;
          }

          core.setFailed("No tag found from release-drafter outputs");
