name: "Check - Url - Lighthouse"
description: "Action to run Lighthouse audits on given URL."
author: Hoverkraft
branding:
  icon: sun
  color: gray-dark

inputs:
  url:
    description: "The URL to audit using Lighthouse."
    required: true
  budget-path:
    description: "The path to the performance budget file. See <https://web.dev/articles/use-lighthouse-for-performance-budgets>."
    required: false
    default: "./budget.json"

runs:
  using: composite
  steps:
    - uses: treosh/lighthouse-ci-action@v12
      with:
        urls: ${{ inputs.url }}
        budgetPath: ${{ inputs.budget-path }}
        uploadArtifacts: true
