---
name: Internal - Main - Continuous Integration

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags: ["*"]

  workflow_dispatch:

  schedule:
    - cron: "25 8 * * 1"

permissions:
  actions: read
  contents: read
  deployments: write
  pages: write
  security-events: write
  statuses: write
  # FIXME: This is a workaround for having workflow actions. See https://github.com/orgs/community/discussions/38659
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/__shared-ci.yml
    secrets: inherit

  release:
    needs: ci
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/release-actions.yml
    with:
      update-all: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'workflow_dispatch' }}
      github-app-id: ${{ vars.CI_BOT_APP_ID }}
    secrets:
      github-app-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}

  sync-docs:
    needs: release
    if: github.event_name != 'schedule' && github.ref == 'refs/heads/main' && needs.release.outputs.artifact-id
    uses: hoverkraft-tech/public-docs/.github/workflows/sync-docs-dispatcher.yml@cd3f060f4c823de3294a7498b8a8617723b8cf53 # 0.2.0
    with:
      github-app-id: ${{ vars.PUBLIC_DOCS_APP_ID }}
      artifact-id: ${{ needs.release.outputs.artifact-id }}
    secrets:
      github-app-key: ${{ secrets.PUBLIC_DOCS_APP_PRIVATE_KEY }}
