---
name: Internal - Main - Continuous Integration

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:

permissions:
  contents: read
  statuses: write
  deployments: write
  # FIXME: This is a workaround for having workflow actions. See https://github.com/orgs/community/discussions/38659
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/__shared-ci.yml

  release:
    needs: ci
    uses: ./.github/workflows/release-actions.yml
    with:
      update-all: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'workflow_dispatch' }}
      github-app-id: ${{ vars.CI_BOT_APP_ID }}
    secrets:
      github-app-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}
