---
name: Need fix to Issue

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:
    #checkov:skip=CKV_GHA_7: required
    inputs:
      manual-commit-ref:
        description: "The SHA of the commit to get the diff for"
        required: true
      manual-base-ref:
        description: |
          By default, the commit entered above is compared to the one directly before it;
          to go back further, enter an earlier SHA here
        required: false

permissions:
  contents: read
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/need-fix-to-issue.yml@d324c777132734fc988c79a74dff3ee0248835fc # 0.25.0
    with:
      manual-commit-ref: ${{ inputs.manual-commit-ref }}
      manual-base-ref: ${{ inputs.manual-base-ref }}
