---
name: Internal - Common Continuous Integration tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@71b85947453f32b5d147ff3ab37351439a92d840 # 0.34.2
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write

  test-action-check-url-lighthouse:
    needs: linter
    uses: ./.github/workflows/__test-action-check-url-lighthouse.yml
    permissions:
      contents: read

  test-action-check-url-ping:
    needs: linter
    uses: ./.github/workflows/__test-action-check-url-ping.yml
    permissions:
      contents: read

  test-action-deploy-argocd-manifest-files:
    needs: linter
    uses: ./.github/workflows/__test-action-deploy-argocd-manifest-files.yml
    permissions:
      contents: read

  test-action-deploy-jekyll-jampack:
    needs: linter
    uses: ./.github/workflows/__test-action-deploy-jekyll-jampack.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write

  test-action-deployment:
    needs: linter
    uses: ./.github/workflows/__test-action-deployment.yml
    permissions:
      contents: read
      deployments: write
      pull-requests: read
    secrets: inherit

  test-action-release-get-configuration:
    needs: linter
    uses: ./.github/workflows/__test-action-release-get-configuration.yml
    permissions:
      contents: read
