---
name: Mark stale issues and pull requests

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/stale.yml@6b5b43e6613bd69904a43d702e60961f494cd92d # 0.19.0
