name: Internal - Tests for "deploy/jekyll" action

on:
  workflow_call:

permissions:
  contents: read

jobs:
  tests:
    name: Tests for "deploy/jekyll" action
    runs-on: ubuntu-latest
    outputs:
      build-path: ${{ steps.deploy-jekyll.outputs.build-path }}
    steps:
      - name: Arrange - Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Act - Deploy Jekyll
        id: deploy-jekyll
        uses: ./actions/deploy/jekyll

      - name: Assert - Check outputs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const assert = require("assert");
            const { existsSync } = require("fs");

            const buildPathOutput = ${{ toJSON(steps.deploy-jekyll.outputs.build-path) }};
            assert(buildPathOutput, `"build-path" output is empty`);


            const buildAssetsPathOutput = ${{ toJSON(steps.deploy-jekyll.outputs.build-path) }};
            assert(buildAssetsPathOutput, `"build-path" output is empty`);

            // Check if the build assets path exists
            if (!existsSync(buildAssetsPathOutput)) {
              throw new Error(`Build assets path does not exist: ${buildAssetsPathOutput}`);
            }

            // Check if the index.html file exists in the build assets path
            const indexFilePath = `${buildAssetsPathOutput}/index.html`;
            if (!existsSync(indexFilePath)) {
              throw new Error(`Jekyll site index.html does not exist in the build assets path: ${indexFilePath}`);
            }
