name: Internal - Tests for "deploy/jekyll" action

on:
  workflow_call:

permissions:
  contents: read

jobs:
  tests-act:
    name: Tests for "deploy/jekyll" action - Act
    runs-on: ubuntu-latest
    outputs:
      build-artifact-name: ${{ steps.deploy-jekyll.outputs.build-artifact-name }}
      build-artifact-path: ${{ steps.deploy-jekyll.outputs.build-artifact-path }}
    steps:
      - name: Arrange - Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Act - Deploy Jekyll
        id: deploy-jekyll
        uses: ./actions/deploy/jekyll

  tests-assert:
    name: Tests for "deploy/jekyll" action - Assert
    runs-on: ubuntu-latest
    needs: tests-act
    steps:
      - name: Assert - Check outputs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const assert = require("assert");

            const buildArtifactNameOutput = ${{ toJSON(needs.tests-act.outputs.build-artifact-name) }};
            assert(buildArtifactNameOutput, `"build-artifact-name" output is empty`);

            const buildAssetsPathOutput = ${{ toJSON(needs.tests-act.outputs.build-artifact-path) }};
            assert(buildAssetsPathOutput, `"build-artifact-path" output is empty`);

      - name: Assert - Download Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ needs.tests-act.outputs.build-artifact-name }}
          path: ${{ needs.tests-act.outputs.build-artifact-path }}

      - name: Assert - Check Jekyll build assets
        run: |
          if [ ! -d "${{ needs.tests-act.outputs.build-artifact-path }}" ]; then
            echo "Build assets path does not exist: ${{ needs.tests-act.outputs.build-artifact-path }}"
            exit 1
          fi

          # Check if the Jekyll site was built correctly
          if [ ! -f "${{ needs.tests-act.outputs.build-artifact-path }}/index.html" ]; then
            echo "Jekyll site index.html does not exist in the build assets path: ${{ needs.tests-act.outputs.build-artifact-path }}"
            exit 1
          fi

      - uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        with:
          name: ${{ needs.tests-act.outputs.build-artifact-name }}
