# Reusable workflow that performs release preparation tasks:
#
# - Add proper labels to pull requests

name: Prepare release

on:
  workflow_call:
    inputs:
      runs-on:
        description: |
          JSON array of runner(s) to use.
          See https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job.
        type: string
        default: '["ubuntu-latest"]'
        required: false
      working-directory:
        description: |
          Working directory for monorepo support.
          If specified, the release configuration file will be placed in `.github/release-configs/{slug}.yml` where slug is derived from the working directory path.
          The configuration will include `include-paths` to filter pull requests to only those that modified files in the specified directory.
        type: string
        required: false
        default: ""
    secrets:
      github-token:
        description: |
          GitHub token with following permissions:

          - `contents: write`
          - `pull-requests: write`

concurrency:
  group: ${{ github.workflow }}-${{ inputs.working-directory }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  prepare:
    runs-on: ${{ fromJson(inputs.runs-on) }}
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_name == github.event.repository.default_branch)
    permissions:
      contents: write
      pull-requests: read
      id-token: write # Needed for getting local workflow actions
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - id: local-workflow-actions
        uses: hoverkraft-tech/ci-github-common/actions/local-workflow-actions@f5847cb398fe65d53794e6aba98ebdfa0801f691 # 0.32.0
        with:
          actions-path: actions

      - id: get-configuration
        uses: ./self-workflow/actions/release/get-configuration
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: release-drafter/release-drafter/autolabeler@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.github-token || secrets.GITHUB_TOKEN || github.token }}
          # config-path is relative to ".github" directory
          config-name: file:${{ steps.get-configuration.outputs.config-path }}

      # jscpd:ignore-start
      - uses: hoverkraft-tech/ci-github-common/actions/local-workflow-actions@f5847cb398fe65d53794e6aba98ebdfa0801f691 # 0.32.0
        if: always() && steps.local-workflow-actions.outputs.repository
        with:
          actions-path: actions
          repository: ${{ steps.local-workflow-actions.outputs.repository }}
          ref: ${{ steps.local-workflow-actions.outputs.ref }}
      # jscpd:ignore-end
